-- PRODUCT: Products catalog (Oracle)
CREATE TABLE PRODUCT (
    CODE VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    PRICE NUMBER(19,4) NOT NULL,
    CONSTRAINT chk_product_price CHECK (PRICE >= 0)
);

-- RAW_MATERIAL: Raw materials inventory
CREATE TABLE RAW_MATERIAL (
    CODE VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    STOCK_QUANTITY NUMBER(19,4) NOT NULL,
    CONSTRAINT chk_raw_material_stock CHECK (STOCK_QUANTITY >= 0)
);

-- PRODUCT_MATERIAL: Bill of materials (join table with required quantities)
CREATE TABLE PRODUCT_MATERIAL (
    PRODUCT_CODE VARCHAR2(50) NOT NULL,
    RAW_MATERIAL_CODE VARCHAR2(50) NOT NULL,
    REQUIRED_QUANTITY NUMBER(19,4) NOT NULL,
    CONSTRAINT pk_product_material PRIMARY KEY (PRODUCT_CODE, RAW_MATERIAL_CODE),
    CONSTRAINT fk_product_material_product FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCT(CODE) ON DELETE CASCADE,
    CONSTRAINT fk_product_material_raw_material FOREIGN KEY (RAW_MATERIAL_CODE) REFERENCES RAW_MATERIAL(CODE) ON DELETE CASCADE,
    CONSTRAINT chk_product_material_quantity CHECK (REQUIRED_QUANTITY > 0)
);
