-- Drop existing tables (order matters due to FKs)
DROP TABLE PRODUCT_MATERIAL;
DROP TABLE PRODUCT;
DROP TABLE RAW_MATERIAL;

-- PRODUCT: Products catalog (with UUID)
CREATE TABLE PRODUCT (
    ID VARCHAR2(36) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    PRICE NUMBER(19,4) NOT NULL,
    CONSTRAINT chk_product_price CHECK (PRICE >= 0)
);

-- RAW_MATERIAL: Raw materials inventory (with UUID)
CREATE TABLE RAW_MATERIAL (
    ID VARCHAR2(36) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    STOCK_QUANTITY NUMBER(19,4) NOT NULL,
    CONSTRAINT chk_raw_material_stock CHECK (STOCK_QUANTITY >= 0)
);

-- PRODUCT_MATERIAL: Bill of materials (with UUID FKs)
CREATE TABLE PRODUCT_MATERIAL (
    PRODUCT_ID VARCHAR2(36) NOT NULL,
    RAW_MATERIAL_ID VARCHAR2(36) NOT NULL,
    REQUIRED_QUANTITY NUMBER(19,4) NOT NULL,
    CONSTRAINT pk_product_material PRIMARY KEY (PRODUCT_ID, RAW_MATERIAL_ID),
    CONSTRAINT fk_product_material_product FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE,
    CONSTRAINT fk_product_material_raw_material FOREIGN KEY (RAW_MATERIAL_ID) REFERENCES RAW_MATERIAL(ID) ON DELETE CASCADE,
    CONSTRAINT chk_product_material_quantity CHECK (REQUIRED_QUANTITY > 0)
);
