# --- Oracle datasource (dev profile - same as production) ---
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=system
quarkus.datasource.password=oracle
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1

# Flyway: use Oracle migrations
quarkus.flyway.locations=db/migration/oracle
